config/routes.rb
Rails.application.routes.draw do
	devise_for :admins
	resources :posts
  
  
  # root to: "posts#index"
  # get 'index', to: 'posts#index'
  
  # get '/posts/index', to: 'posts#index'
  # get '/posts/list', to: 'posts#list'
  # get '/posts/new', to: 'posts#create'
  # get '/posts/:id', to: 'posts#show'
  # get '/posts/edit', to: 'posts#edit'



end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :content, presence: true
	
	has_attached_file :image, styles: { large:"415x230",medium: "200x200#",small: "175x175#" ,thumb: "112x112#" }, default_url: "/images/:style/default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "default" %>
    <%= javascript_include_tag "default", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Редактировать новость</h1>



<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="text-center">Самые интересные новости в сети!</h1>
<!-- <div class="container"> -->
	<div class="btn btn-show"></div>
	<div class="row">
		<div class="col-md-offset-1">
		<% @posts.each do |post| %>
			<div class="col-md-2">
				<div class="front-image">
					<%= image_tag post.image.url(:small) %>
				</div>
				<p class="front-post">
					<%= post.content %>
				</p>
				<% if admin_signed_in? %>
					<div class="button btn btn-success">
						<%= link_to 'Edit', edit_post_path(post) %> 
					</div>
					<div class="button btn btn-danger">
			  			<%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
			  		</div>
					<div class="button btn btn-info">
						<%= link_to "Show post", post %>
					</div>
					<div class="button btn btn-primary">
						<%= link_to 'New Post', new_post_path  %>
					</div>
				<% end %>
			</div>
		<% end %>
			
		
		<div class="col-md-offset-1">
	</div>
	

</div>

<!-- </div> -->
<!-- -->

app/views/posts/list.html.erb
<% @posts.each do |post| %>
	<tr>
		<td><%= post.title %>  </td>
		<td><%= post.content %></td>
		<td><%= image_tag post.image.url(:small) %>	</td>
		<td><%= link_to "Show", post  %></td>
		<td><%= link_to "Edit", edit_post_path(post) %></td>
		<td><%= link_to "Destroy", post, method: :delete, data: {confirm: "Are you sure?"} %></td>
	</tr>
<% end %>

app/views/posts/new.html.erb
	<h1>Добавить новость</h1>

	
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>